### ISSUE TITLE
mlcp-9.0.9 WARNING KerberosUtil

### ISSUE THREAD

**Issue by prestonmcgowan** [marklogic/marklogic-contentpump#106] opened 2019-07-18 16:02 UTC
I received the following WARNING when running mlcp-9.0.9

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.hadoop.security.authentication.util.KerberosUtil (file:/Users/pmcgowan/tools/mlcp-9.0.9/lib/hadoop-auth-2.6.0.jar) to method sun.security.krb5.Config.getInstance()
WARNING: Please consider reporting this to the maintainers of org.apache.hadoop.security.authentication.util.KerberosUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**Comment by yunzvanessa** [comment] 2019-08-06 21:11
Hi Preston,

This warning is caused by the enforcement of strong encapsulation in OpenJDK>=9. Any access to non-public classes and non-exported packages is marked as illegal access in OpenJDK>=9. Hadoop mapreduce library uses Kerberos for authentication. So what causes the problem is Hadoop library, not MLCP.

This warning currently won't affect the functionality of MLCP. However, if illegal access is removed in future OpenJDK, we need to rely on Hadoop to fix this problem. Please refer to: http://openjdk.java.net/jeps/261#Relaxed-strong-encapsulation.

Hope this helps,
Vanessa

**Closed** 2019-08-23 23:55 UTC
Labels: minor, mlcp, not a bug, will not fix
